/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// Precache assets generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST)

// Take control immediately
self.skipWaiting()
clientsClaim()

// Push Notification Handler
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push received:', event)

  let notificationData = {
    title: 'Unicorns Łódź',
    body: 'Nowe powiadomienie',
    icon: '/unicorns-logo.png',
    badge: '/unicorns-logo.png',
    data: {
      url: '/'
    }
  }

  // Parse push data
  if (event.data) {
    try {
      const data = event.data.json()
      notificationData = {
        ...notificationData,
        ...data
      }
    } catch (e) {
      console.error('[Service Worker] Error parsing push data:', e)
      notificationData.body = event.data.text()
    }
  }

  const promiseChain = self.registration.showNotification(
    notificationData.title,
    {
      body: notificationData.body,
      icon: notificationData.icon,
      badge: notificationData.badge,
      data: notificationData.data,
      tag: 'unicorns-notification',
      requireInteraction: false
    }
  )

  event.waitUntil(promiseChain)
})

// Notification Click Handler
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification clicked:', event)

  event.notification.close()

  const urlToOpen = event.notification.data?.url || '/'

  const promiseChain = self.clients.matchAll({
    type: 'window',
    includeUncontrolled: true
  })
    .then((windowClients) => {
      // Check if app is already open
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus()
        }
      }

      // Otherwise open new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })

  event.waitUntil(promiseChain)
})

console.log('[Service Worker] Custom SW with push notifications loaded')
